spring:
  cloud:
    stream:
      bindings:
        process-in-0:
          destination: dataIn
          binder: kafka
        process-out-0:
          destination: dataOut
          binder: rabbit
        #Test sink binding (used for testing)
        sendTestData-out-0:
          destination: dataIn
          binder: kafka
        #Test sink binding (used for testing)
        receive-in-0:
          destination: dataOut
          binder: rabbit
      function:
        definition: sendTestData;process;receive

