originator: KinesisProducer
server:
 port: 64398
management:
  server:
    port: 8082
    servlet:
      context-path: /manage

spring:
  security:
    user:
      name: admin
      password: 2c76788d-e661-49fd-baba-4b41e7c1dd47
  cloud:
    stream:
      bindings:
        produceOrder-out-0:
          destination: test_stream
          content-type: application/json
          producer:
            partitionKeyExpression: "1"
        processOrder-in-0:
          destination: test_stream
          content-type: application/json
    function:
      definition: processOrder;produceOrder


cloud:
  aws:
    region:
      static: eu-west-1


logging:
  level:
    com:
      amazonaws: INFO
    org:
      apache:
        http: INFO
