spring:
  cloud:
    stream:
      bindings:
        process-in-0:
          destination: dataIn
          binder: kafka1
        process-out-0:
          destination: dataOut
          binder: kafka2
        #Test sink binding (used for testing)
        sendTestData-out-0:
          destination: dataIn
          binder: kafka1
        #Test sink binding (used for testing)
        receive-in-0:
          destination: dataOut
          binder: kafka2
      function:
        definition: sendTestData;process;receive
      binders:
        kafka1:
          type: kafka
          environment:
            spring:
              cloud:
                stream:
                  kafka:
                    binder:
                      brokers: ${kafkaBroker1}
                      zkNodes: ${zk1}
        kafka2:
          type: kafka
          environment:
            spring:
              cloud:
                stream:
                  kafka:
                    binder:
                      brokers: ${kafkaBroker2}
                      zkNodes: ${zk2}