spring:
  cloud:
    stream:
      bindings:
        process-in-0:
          destination: sensor-topic
      schemaRegistryClient:
        endpoint: http://localhost:8081
    schema:
      avro:
        schema-locations: classpath:avro/sensor.avsc
        subjectNamePrefix:  sensor-topic-value
        subjectNamingStrategy: org.springframework.cloud.schema.registry.avro.SubjectPrefixOnlyNamingStrategy
server.port: 9999
