spring:
  cloud:
    stream:
      bindings:
        process-in-0:
          destination: person-event
      kafka:
          binder:
              configuration:
                isolation.level: read_committed

server.port: 9999
